### ISSUE TITLE
Waarom dit publiceren op een gesloten platform?

### ISSUE THREAD

**Issue by Hilbrand** [codefornl/5staropensource#2]
Prima idee om dit op deze manier te publiceren en aandacht te vestigen via een repository en GitHub is ook een mooi platform. Maar GitHub is ook een gesloten platform. Er is bijvoorbeeld een prima alternatief, die wel open source is en bovendien een Nederlands tintje heeft: [gitlab.org](gitlab.org). Niet geheel toevallig dat het groot Rijks ICT project AERIUS de broncode via dit medium heeft vrijgegeven: https://gitlab.com/AERIUS/

Overigens is het de overheid voor sommige projecten vanwege de juridische status de vraag of het mogelijk is om elke commit te publiceren ofwel 5-sterren te halen. Ik vermoed dat juristen en beleidsmakers daar erg zenuwachtig van zouden worden en dus veel weerstand zullen opwerpen voor open source maken en krijg je de verkeerde discussies die het doel voorbij schieten. Een duidelijk doel van wat met open source maken bereikt wil worden kan dan helpen bij een invulling te geven hoe het open source te maken. Bijvoorbeeld om transparantie te bereiken kan beperkt worden tot de officiële releases of iets dergelijks.

**Comment by milovanderlinden** [comment]
Beste Hilbrand,

Dank je wel dat je meedenkt, dat waarderen we. Gitlab is inderdaad een heel mooi product. Ook al zijn we nog niet heel actief, codefornl is ook geregistreerd https://gitlab.com/codefornl. 

Github is voor ons momenteel vergelijkbaar met Facebook; er is een grotere community, dus je bereikt (op dit moment) meer mensen. Daarnaast doen wij alles open. Het kan dus niet zo zijn dat we een eigen gitlab omgeving draaien waarvoor we ook nog de toegang moeten controleren en beheren. 

Als straks blijkt dat gitlab beter past, dan gaan wij wellicht met mirroring aan de slag om te zorgen dat we meerdere ingangen laten ontstaan. Uiteraard is het dan wel belangrijk dat omgevingen altijd exact synchroon lopen! Het belangrijkste voor ons blijft dat ontwikkelaars onze projecten kunnen vinden.

Wat betreft je tweede opmerking, we begrijpen de uitdagingen waar onze overheden voor staan. Maar daar betalen wij (Nederlanders) ze dan ook goed voor. Persoonlijk wil ik ook af van "de burger als klant", in mijn ogen zijn we de aandeelhouders. Bij Code For NL worden we enthousiast van zenuwachtige beleidsmakers en juristen en gaan graag de dialoog met hen aan om te helpen dit proces soepel te laten lopen. Ken je mensen uit het beleidsveld die worstellen met deze vraagstukken? Laat ze dan alsjeblieft contact met ons opnemen.

**Comment by jgroenen** [comment]
Interessante discussie voor op één van de Code for NL meetups.
